### ISSUE TITLE
Modify circuits pins lead to a compilation error

### ISSUE THREAD

**Issue by Farrand** [CyberCRI/RedWire#532]
The chips options does not respond anymore (mute, edit, etc) after modifying the Pins of a circuit in the top left window

COMPILATION ERRORS:
  TypeError: Cannot read property 'board' of undefined
    at searchRecursive (https://redwire.io/src/app/redWire.js:127:66)
    at searchRecursive (https://redwire.io/src/app/redWire.js:133:11)
    at searchRecursive (https://redwire.io/src/app/redWire.js:133:11)
    at searchRecursive (https://redwire.io/src/app/redWire.js:133:11)
    at searchRecursive (https://redwire.io/src/app/redWire.js:133:11)
    at Object.RW.listCircuitMeta (https://redwire.io/src/app/redWire.js:138:12)
    at loadGame (https://redwire.io/src/app/puppet.js:428:23)
    at https://redwire.io/src/app/puppet.js:617:18

**Comment by Farrand** [comment]
If the project is closed and openned again, the problem persist. The only solution is to erase all instances of the circuit modified from the main circuit.
